### ISSUE TITLE
【追加注文/配達状況】追加注文と配達状況を分離する

### ISSUE THREAD

**Issue by matsu0731** [matsu0731/tutti_management_system#4]
現状「配達状況」画面に追加注文ボタンを配置しているが，これを取り除く．追加注文はサイドバーからのみアクセスするようにする．

**Comment by amatsun** [comment]
やること：
１．色ごとの説明追加
２．追加注文の削除
３．表示バグの修正

**Comment by matsu0731** [comment]
waiter.phpはファイル名をdelivery_status.phpに変更する．画面タイトルは「配達状況」とする．
status_confirm.phpでは，画面上で席番号を明示してください．逆に「お客様ID」は非表示としてください．

**Comment by matsu0731** [comment]
完了
